const menu = [
  {
    id: 1,
    title: 'fluffy pancakes',
    category: 'breakfast',
    price: 9.99,
    img: './images/item-1.jpeg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
  },
  {
    id: 2,
    title: 'aussie style diner',
    category: 'lunch',
    price: 18.0,
    img: './images/item-2.jpeg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
  },
  {
    id: 3,
    title: 'milkshake',
    category: 'shakes',
    price: 10.0,
    img: './images/item-3.jpeg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
  },
  {
    id: 4,
    title: 'breakfast delight',
    category: 'breakfast',
    price: 22.0,
    img: './images/item-4.jpeg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
  },
  {
    id: 5,
    title: 'egg special',
    category: 'breakfast',
    price: 12.5,
    img: './images/item-5.jpeg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
  },
  {
    id: 6,
    title: 'chocolate dessert',
    category: 'shakes',
    price: 9.0,
    img: './images/item-6.jpeg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
  },
  {
    id: 7,
    title: 'lunch special',
    category: 'lunch',
    price: 28.99,
    img: './images/item-7.jpeg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
  },
  {
    id: 8,
    title: 'everything fish',
    category: 'lunch',
    price: 25.0,
    img: './images/item-8.jpeg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
  },
  {
    id: 9,
    title: `everyone's favroite`,
    category: 'shakes',
    price: 17.5,
    img: './images/item-9.jpeg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
  },
];
export default menu;
